[WIP] Fix errors in build
microsoft/opentelemetry-azure-monitor-python pull request #50
Opened 2020-03-10 22:23 UTC by lzchen

2020-03-11 00:06 UTC, hectorhdzg approved these changes

2020-03-11 02:06 UTC, hectorhdzg commented
I fixed tons of lint issues in #51 and lint check is green now, sorry for the work overlap apparently we both tried to fix lint and test issues

2020-03-11 02:28 UTC, hectorhdzg requested changes
Lint issues are plenty, apparently lint was not running correctly in my box and I introduced bunch of them in latest PRs, please take a look at #51 CI is currently passing

2020-03-12 21:53 UTC, lzchen commented
Closing and opening [#53]

2020-03-12 21:53 UTC, closed without merging